-- ==========================================
-- DIM_USER
-- ==========================================
CREATE OR REPLACE TABLE DIM_USER (
    USER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    USER_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PASSWORD_HASH VARCHAR(500),
    STATUS BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,

    CONSTRAINT pk_DIM_USER PRIMARY KEY (USER_KEY),
    CONSTRAINT UK_DIM_USER UNIQUE (USER_ID)
);

-- ==========================================
-- DIM_ADDRESS
-- ==========================================
CREATE OR REPLACE TABLE DIM_ADDRESS (
    ADDRESS_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ADDRESS_ID NUMBER NOT NULL,
    USER_KEY NUMBER NOT NULL,
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    DISTRICT VARCHAR(100),
    CITY VARCHAR(100),
    VILLAGE VARCHAR(100),
    ZIPCODE VARCHAR(20),
    ADDRESS_TYPE VARCHAR(50),

    CONSTRAINT PK_DIM_ADDRESS PRIMARY KEY (ADDRESS_KEY),
    CONSTRAINT UK_DIM_ADDRESS UNIQUE (ADDRESS_ID),
    CONSTRAINT FK_DIM_ADDRESS_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY)
);


-- ==========================================
-- DIM_MOBILE
-- ==========================================
CREATE OR REPLACE TABLE DIM_MOBILE (
    MOBILE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    MOBILE_ID NUMBER NOT NULL,
    USER_KEY NUMBER NOT NULL,
    COUNTRY_CODE VARCHAR(10),
    PHONE_NUMBER VARCHAR(20),
    IS_PRIMARY BOOLEAN,

    CONSTRAINT PK_DIM_MOBILE PRIMARY KEY (MOBILE_KEY),
    CONSTRAINT UK_DIM_MOBILE UNIQUE (MOBILE_ID),
    CONSTRAINT FK_DIM_MOBILE_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY)
);

-- ==========================================
-- DIM_ROLE
-- ==========================================
CREATE OR REPLACE TABLE DIM_ROLE (
    ROLE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ROLE_ID NUMBER NOT NULL,
    ROLE_NAME VARCHAR(100),

    CONSTRAINT PK_DIM_ROLE PRIMARY KEY (ROLE_KEY),
    CONSTRAINT UK_DIM_ROLE UNIQUE (ROLE_ID)
);

-- ==========================================
-- BRIDGE_USER_ROLE
-- ==========================================
CREATE OR REPLACE TABLE BRIDGE_USER_ROLE (
    BRIDGE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    USER_KEY NUMBER NOT NULL,
    ROLE_KEY NUMBER NOT NULL,

    CONSTRAINT PK_BRIDGE_USER_ROLE PRIMARY KEY (BRIDGE_KEY),

    CONSTRAINT FK_BRIDGE_USER_ROLE_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_BRIDGE_USER_ROLE_ROLE
        FOREIGN KEY (ROLE_KEY)
        REFERENCES DIM_ROLE(ROLE_KEY)
);

-- ==========================================
-- DIM_DEVICE
-- ==========================================
CREATE OR REPLACE TABLE DIM_DEVICE (
    DEVICE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    DEVICE_NAME VARCHAR(100),
    BROWSER VARCHAR(100),

    CONSTRAINT PK_DIM_DEVICE PRIMARY KEY (DEVICE_KEY)
);
-- ==========================================
-- DIM_DATE
-- ==========================================
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER NOT NULL,
    FULL_DATE DATE,
    DAY NUMBER,
    MONTH NUMBER,
    QUARTER NUMBER,
    YEAR NUMBER,
    DAY_NAME VARCHAR(20),

    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);
-- ==========================================
-- DIM_TIME
-- ==========================================
CREATE OR REPLACE TABLE DIM_TIME (
    TIME_KEY NUMBER NOT NULL,
    HOUR NUMBER,
    MINUTE NUMBER,
    SECOND NUMBER,

    CONSTRAINT PK_DIM_TIME PRIMARY KEY (TIME_KEY)
);
-- ==========================================
-- DIM_IP
-- ==========================================
CREATE OR REPLACE TABLE DIM_IP (
    IP_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    IP_ADDRESS VARCHAR(45),

    CONSTRAINT PK_DIM_IP PRIMARY KEY (IP_KEY)
);

-- ==========================================
-- DIM_LOGIN_STATUS
-- ==========================================
CREATE OR REPLACE TABLE DIM_LOGIN_STATUS (
    STATUS_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    LOGIN_STATUS VARCHAR(50),

    CONSTRAINT PK_DIM_LOGIN_STATUS
        PRIMARY KEY (STATUS_KEY)
);
-- ==========================================
-- DIM_ACTIVITY
-- ==========================================
CREATE OR REPLACE TABLE DIM_ACTIVITY (
    ACTIVITY_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ACTIVITY_NAME VARCHAR(100),

    CONSTRAINT PK_DIM_ACTIVITY
        PRIMARY KEY (ACTIVITY_KEY)
);
-- ==========================================
-- DIM_NOTIFICATION_TYPE
-- ==========================================
CREATE OR REPLACE TABLE DIM_NOTIFICATION_TYPE (
    NOTIFICATION_TYPE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    NOTIFICATION_TYPE VARCHAR(100),

    CONSTRAINT PK_DIM_NOTIFICATION_TYPE
        PRIMARY KEY (NOTIFICATION_TYPE_KEY)
);


-- ==========================================
-- FACT_LOGIN
-- ==========================================
CREATE OR REPLACE TABLE FACT_LOGIN (
    LOGIN_FACT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    USER_KEY NUMBER NOT NULL,
    DEVICE_KEY NUMBER NOT NULL,
    IP_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,
    TIME_KEY NUMBER NOT NULL,
    STATUS_KEY NUMBER NOT NULL,

    LOGIN_COUNT NUMBER DEFAULT 1,

    CONSTRAINT PK_FACT_LOGIN PRIMARY KEY (LOGIN_FACT_KEY),

    CONSTRAINT FK_FACT_LOGIN_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_FACT_LOGIN_DEVICE
        FOREIGN KEY (DEVICE_KEY)
        REFERENCES DIM_DEVICE(DEVICE_KEY),

    CONSTRAINT FK_FACT_LOGIN_IP
        FOREIGN KEY (IP_KEY)
        REFERENCES DIM_IP(IP_KEY),

    CONSTRAINT FK_FACT_LOGIN_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY),

    CONSTRAINT FK_FACT_LOGIN_TIME
        FOREIGN KEY (TIME_KEY)
        REFERENCES DIM_TIME(TIME_KEY),

    CONSTRAINT FK_FACT_LOGIN_STATUS
        FOREIGN KEY (STATUS_KEY)
        REFERENCES DIM_LOGIN_STATUS(STATUS_KEY)
);

-- ==========================================
-- FACT_ACTIVITY
-- ==========================================
CREATE OR REPLACE TABLE FACT_ACTIVITY (
    ACTIVITY_FACT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    USER_KEY NUMBER NOT NULL,
    ACTIVITY_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,
    TIME_KEY NUMBER NOT NULL,

    ACTIVITY_COUNT NUMBER DEFAULT 1,

    CONSTRAINT PK_FACT_ACTIVITY PRIMARY KEY (ACTIVITY_FACT_KEY),

    CONSTRAINT FK_FACT_ACTIVITY_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_FACT_ACTIVITY_ACTIVITY
        FOREIGN KEY (ACTIVITY_KEY)
        REFERENCES DIM_ACTIVITY(ACTIVITY_KEY),

    CONSTRAINT FK_FACT_ACTIVITY_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY),

    CONSTRAINT FK_FACT_ACTIVITY_TIME
        FOREIGN KEY (TIME_KEY)
        REFERENCES DIM_TIME(TIME_KEY)
);

-- ==========================================
-- FACT_NOTIFICATION
-- ==========================================
CREATE OR REPLACE TABLE FACT_NOTIFICATION (
    NOTIFICATION_FACT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    USER_KEY NUMBER NOT NULL,
    NOTIFICATION_TYPE_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,
    TIME_KEY NUMBER NOT NULL,

    NOTIFICATION_SENT NUMBER DEFAULT 0,
    NOTIFICATION_READ NUMBER DEFAULT 0,

    CONSTRAINT PK_FACT_NOTIFICATION PRIMARY KEY (NOTIFICATION_FACT_KEY),

    CONSTRAINT FK_FACT_NOTIFICATION_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_FACT_NOTIFICATION_TYPE
        FOREIGN KEY (NOTIFICATION_TYPE_KEY)
        REFERENCES DIM_NOTIFICATION_TYPE(NOTIFICATION_TYPE_KEY),

    CONSTRAINT FK_FACT_NOTIFICATION_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY),

    CONSTRAINT FK_FACT_NOTIFICATION_TIME
        FOREIGN KEY (TIME_KEY)
        REFERENCES DIM_TIME(TIME_KEY)
);

CREATE SCHEMA Ecommerce_DW.Seller_Model;
USE SCHEMA Seller_Model;

// -------------------------------------------------------------------------------------------------------------------------------------

-- ==========================================
-- DIM_SELLER
-- ==========================================
CREATE OR REPLACE TABLE DIM_SELLER (
    SELLER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    SELLER_ID NUMBER NOT NULL,
    GST_NUMBER VARCHAR(20),
    PAN VARCHAR(10),
    BUSINESS_NAME VARCHAR(255),
    BUSINESS_EMAIL VARCHAR(255),

    CONSTRAINT PK_DIM_SELLER PRIMARY KEY (SELLER_KEY),
    CONSTRAINT UK_DIM_SELLER UNIQUE (SELLER_ID)
);



// -------------------------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA Ecommerce_DW.Order_Model;
USE SCHEMA Order_Model;
-- ==========================================
-- DIM_ORDERS
-- ==========================================
CREATE OR REPLACE TABLE DIM_ORDERS (
    ORDER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ORDER_ID NUMBER NOT NULL,
    USER_KEY NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2),
    ORDER_STATUS VARCHAR(30),

    CONSTRAINT PK_DIM_ORDERS PRIMARY KEY (ORDER_KEY),
    CONSTRAINT UK_DIM_ORDERS UNIQUE (ORDER_ID),

    CONSTRAINT FK_DIM_ORDERS_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES User_model.DIM_USER(USER_KEY)
);

/* -- ==========================================
-- FACT_ORDER_ITEMS -------------------------------------
-- ==========================================
CREATE OR REPLACE TABLE FACT_ORDER_ITEMS (
    ORDER_ITEM_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ORDER_ITEM_ID NUMBER NOT NULL,

    ORDER_KEY NUMBER NOT NULL,
    SELLER_PRODUCT_KEY NUMBER NOT NULL,

    QUANTITY NUMBER,

    UNIT_PRICE NUMBER(10,2),

    COST_PRICE NUMBER(10,2),

    DISCOUNT_AMOUNT NUMBER(10,2),

    TAX_AMOUNT NUMBER(10,2),

    SHIPPING_AMOUNT NUMBER(10,2),

    REVENUE NUMBER(12,2),

    PROFIT NUMBER(12,2),

    MARGIN_PERCENT NUMBER(5,2),

    CONSTRAINT PK_FACT_ORDER_ITEMS
        PRIMARY KEY (ORDER_ITEM_KEY),

    CONSTRAINT UK_FACT_ORDER_ITEMS
        UNIQUE (ORDER_ITEM_ID),

    CONSTRAINT FK_FACT_ORDER_ITEMS_ORDER
        FOREIGN KEY (ORDER_KEY)
        REFERENCES DIM_ORDERS(ORDER_KEY),

    CONSTRAINT FK_FACT_ORDER_ITEMS_SELLER_PRODUCT
        FOREIGN KEY (SELLER_PRODUCT_KEY)
        REFERENCES Seller_model.BRIDGE_PRODUCT_SELLERS(SELLER_PRODUCT_KEY)
);*/

-- ==========================================
-- DIM_COUPONS
-- ==========================================
CREATE OR REPLACE TABLE DIM_COUPONS (
    COUPON_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    COUPON_ID NUMBER NOT NULL,
    COUPON_CODE VARCHAR(30) NOT NULL,
    DISCOUNT_PERCENTAGE NUMBER(5,2),
    MINIMUM_AMOUNT NUMBER(10,2),
    EXPIRY_DATE DATE,
    IS_ACTIVE BOOLEAN,

    CONSTRAINT PK_DIM_COUPONS PRIMARY KEY (COUPON_KEY),
    CONSTRAINT UK_DIM_COUPONS_ID UNIQUE (COUPON_ID),
    CONSTRAINT UK_DIM_COUPONS_CODE UNIQUE (COUPON_CODE)
);

-- ==========================================
-- BRIDGE_ORDER_COUPONS
-- ==========================================
CREATE OR REPLACE TABLE BRIDGE_ORDER_COUPONS (
    ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    ORDER_KEY NUMBER NOT NULL,
    COUPON_KEY NUMBER NOT NULL,

    DISCOUNT_AMOUNT NUMBER(10,2),

    CONSTRAINT PK_BRIDGE_ORDER_COUPONS PRIMARY KEY (ID),

    CONSTRAINT FK_BRIDGE_ORDER_COUPONS_ORDER
        FOREIGN KEY (ORDER_KEY)
        REFERENCES DIM_ORDERS(ORDER_KEY),

    CONSTRAINT FK_BRIDGE_ORDER_COUPONS_COUPON
        FOREIGN KEY (COUPON_KEY)
        REFERENCES DIM_COUPONS(COUPON_KEY)
);

// --------------------------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA Ecommerce_DW.Return_Refund;
USE SCHEMA Return_Refund;
-- ==========================================
-- FACT_RETURNS
-- ==========================================
CREATE OR REPLACE TABLE FACT_RETURNS (
    RETURN_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RETURN_ID NUMBER NOT NULL,

    ORDER_ITEM_ID NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,

    REASON VARCHAR(200),
    RETURN_STATUS VARCHAR(30),

    REQUESTED_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_FACT_RETURNS PRIMARY KEY (RETURN_KEY),
    CONSTRAINT UK_FACT_RETURNS UNIQUE (RETURN_ID),

    CONSTRAINT FK_FACT_RETURNS_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES user_model.DIM_DATE(DATE_KEY)
);

-- ==========================================
-- FACT_REFUNDS
-- ==========================================
CREATE OR REPLACE TABLE FACT_REFUNDS (
    REFUND_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    REFUND_ID NUMBER NOT NULL,

    RETURN_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,

    REFUND_AMOUNT NUMBER(10,2),
    REFUND_STATUS VARCHAR(30),

    REFUNDED_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_FACT_REFUNDS PRIMARY KEY (REFUND_KEY),
    CONSTRAINT UK_FACT_REFUNDS UNIQUE (REFUND_ID),

    CONSTRAINT FK_FACT_REFUNDS_RETURN
        FOREIGN KEY (RETURN_KEY)
        REFERENCES FACT_RETURNS(RETURN_KEY),

    CONSTRAINT FK_FACT_REFUNDS_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES user_model.DIM_DATE(DATE_KEY)
);

-- ==========================================
-- FACT_REVIEWS
-- ==========================================
CREATE OR REPLACE TABLE FACT_REVIEWS (
    REVIEW_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    REVIEW_ID NUMBER NOT NULL,

    ORDER_ITEM_ID NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,

    RATING NUMBER(1),
    COMMENT VARCHAR(500),

    REVIEWED_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_FACT_REVIEWS PRIMARY KEY (REVIEW_KEY),
    CONSTRAINT UK_FACT_REVIEWS UNIQUE (REVIEW_ID),

    CONSTRAINT FK_FACT_REVIEWS_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES user_model.DIM_DATE(DATE_KEY)
);

// ------------------------------------------------------------------------------------------------------------------------------------

CREATE SCHEMA Ecommerce_DW.Shipments_Model;
USE SCHEMA Shipments_Model;

-- ==========================================
-- FACT_SHIPMENTS
-- ==========================================
CREATE OR REPLACE TABLE FACT_SHIPMENTS (
    SHIPMENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    SHIPMENT_ID NUMBER NOT NULL,

    ORDER_KEY NUMBER NOT NULL,

    TRACKING_NUMBER VARCHAR(100),
    COURIER_NAME VARCHAR(100),
    SHIPMENT_STATUS VARCHAR(30),

    SHIPPING_CHARGE NUMBER(10,2),

    SHIPPED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    EXPECTED_DELIVERY_DATE DATE,

    DELIVERED_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_FACT_SHIPMENTS
        PRIMARY KEY (SHIPMENT_KEY),

    CONSTRAINT UK_FACT_SHIPMENTS
        UNIQUE (SHIPMENT_ID),

    CONSTRAINT UK_FACT_SHIPMENTS_TRACKING
        UNIQUE (TRACKING_NUMBER),

    CONSTRAINT FK_FACT_SHIPMENTS_ORDER
        FOREIGN KEY (ORDER_KEY)
        REFERENCES ORDER_MODEL.DIM_ORDERS(ORDER_KEY)
);


-- ==========================================
-- DIM_SHIPMENT_TRACKING
-- ==========================================
CREATE OR REPLACE TABLE DIM_SHIPMENT_TRACKING (
    TRACKING_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    TRACKING_ID NUMBER NOT NULL,

    SHIPMENT_KEY NUMBER NOT NULL,

    LOCATION VARCHAR(100),
    STATUS VARCHAR(50),

    UPDATED_AT TIMESTAMP,

    CONSTRAINT PK_DIM_SHIPMENT_TRACKING PRIMARY KEY (TRACKING_KEY),
    CONSTRAINT UK_DIM_SHIPMENT_TRACKING UNIQUE (TRACKING_ID),

    CONSTRAINT FK_DIM_SHIPMENT_TRACKING_SHIPMENT
        FOREIGN KEY (SHIPMENT_KEY)
        REFERENCES FACT_SHIPMENTS(SHIPMENT_KEY)
);

// ------------------------------------------------------------------------------------------------------------------------------------


CREATE SCHEMA Ecommerce_DW.payments_Model;
USE SCHEMA payments_Model;
-- ==========================================
-- DIM_PAYMENT_METHOD
-- ==========================================
CREATE OR REPLACE TABLE DIM_PAYMENT_METHOD (
    PAYMENT_METHOD_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PAYMENT_METHOD_ID NUMBER NOT NULL,
    METHOD_NAME VARCHAR(30) NOT NULL,

    CONSTRAINT PK_DIM_PAYMENT_METHOD
        PRIMARY KEY (PAYMENT_METHOD_KEY),

    CONSTRAINT UK_DIM_PAYMENT_METHOD_ID
        UNIQUE (PAYMENT_METHOD_ID),

    CONSTRAINT UK_DIM_PAYMENT_METHOD_NAME
        UNIQUE (METHOD_NAME)
);

-- ==========================================
-- FACT_PAYMENTS
-- ==========================================
CREATE OR REPLACE TABLE FACT_PAYMENTS (
    PAYMENT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PAYMENT_ID NUMBER NOT NULL,

    ORDER_KEY NUMBER NOT NULL,
    PAYMENT_METHOD_KEY NUMBER NOT NULL,

    AMOUNT NUMBER(10,2),
    PAYMENT_STATUS VARCHAR(30),
    TRANSACTION_ID VARCHAR(100),
    PAID_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_FACT_PAYMENTS
        PRIMARY KEY (PAYMENT_KEY),

    CONSTRAINT UK_FACT_PAYMENTS
        UNIQUE (PAYMENT_ID),

    CONSTRAINT UK_FACT_PAYMENTS_TRANSACTION
        UNIQUE (TRANSACTION_ID),

    CONSTRAINT FK_FACT_PAYMENTS_ORDER
        FOREIGN KEY (ORDER_KEY)
        REFERENCES order_model.DIM_ORDERS(ORDER_KEY),

    CONSTRAINT FK_FACT_PAYMENTS_METHOD
        FOREIGN KEY (PAYMENT_METHOD_KEY)
        REFERENCES DIM_PAYMENT_METHOD(PAYMENT_METHOD_KEY)
);

// ------------------------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA Ecommerce_DW.Cart_Model;
USE SCHEMA Cart_Model;
-- ==========================================
-- DIM_CART
-- ==========================================
CREATE OR REPLACE TABLE DIM_CART (
    CART_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CART_ID NUMBER NOT NULL,

    USER_KEY NUMBER NOT NULL,

    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,

    STATUS VARCHAR(20),

    CONSTRAINT PK_DIM_CART PRIMARY KEY (CART_KEY),

    CONSTRAINT UK_DIM_CART UNIQUE (CART_ID),

    CONSTRAINT FK_DIM_CART_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES user_model.DIM_USER(USER_KEY)
);


-- ==========================================
-- FACT_CART_ITEMS
-- ==========================================
CREATE OR REPLACE TABLE FACT_CART_ITEMS (
    CART_ITEM_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CART_ITEM_ID NUMBER NOT NULL,

    CART_KEY NUMBER NOT NULL,

    SELLER_PRODUCT_ID NUMBER NOT NULL,

    QUANTITY NUMBER,

    UNIT_PRICE NUMBER(10,2),

    ADDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_CART_ITEMS
        PRIMARY KEY (CART_ITEM_KEY),

    CONSTRAINT UK_FACT_CART_ITEMS
        UNIQUE (CART_ITEM_ID),

    CONSTRAINT FK_FACT_CART_ITEMS_CART
        FOREIGN KEY (CART_KEY)
        REFERENCES DIM_CART(CART_KEY)
);


-- ==========================================
-- FACT_WISHLIST
-- ==========================================
CREATE OR REPLACE TABLE FACT_WISHLIST (
    WISHLIST_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    WISHLIST_ID NUMBER NOT NULL,

    USER_KEY NUMBER NOT NULL,

    SELLER_PRODUCT_ID NUMBER NOT NULL,

    ADDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_WISHLIST
        PRIMARY KEY (WISHLIST_KEY),

    CONSTRAINT UK_FACT_WISHLIST
        UNIQUE (WISHLIST_ID),

    CONSTRAINT FK_FACT_WISHLIST_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES user_model.DIM_USER(USER_KEY)
);


// ------------------------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA Ecommerce_DW.Product_Model;
USE SCHEMA Product_Model;
-- ==========================================
-- DIM_BRAND
-- ==========================================

CREATE OR REPLACE TABLE DIM_BRAND (
    BRAND_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    BRAND_ID NUMBER NOT NULL,
    BRAND_NAME VARCHAR(100) NOT NULL,

    CONSTRAINT PK_DIM_BRAND PRIMARY KEY (BRAND_KEY),
    CONSTRAINT UK_DIM_BRAND_ID UNIQUE (BRAND_ID),
    CONSTRAINT UK_DIM_BRAND_NAME UNIQUE (BRAND_NAME)
);

-- ==========================================
-- DIM_CATEGORY
-- ==========================================

CREATE OR REPLACE TABLE DIM_CATEGORY (
    CATEGORY_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CATEGORY_ID NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR(100) NOT NULL,

    CONSTRAINT PK_DIM_CATEGORY PRIMARY KEY (CATEGORY_KEY),
    CONSTRAINT UK_DIM_CATEGORY_ID UNIQUE (CATEGORY_ID),
    CONSTRAINT UK_DIM_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);

-- ==========================================
-- DIM_PRODUCTS
-- ==========================================

CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PRODUCT_ID NUMBER NOT NULL,

    PRODUCT_NAME VARCHAR(100),

    CATEGORY_KEY NUMBER,
    BRAND_KEY NUMBER,

    MODEL VARCHAR(100),
    PRODUCT_MARKET_PRICE NUMBER(10,2),

    DESCRIPTION VARCHAR(500),

    WEIGHT NUMBER(10,2),
    DIMENSIONS VARCHAR(200),

    CREATED_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_DIM_PRODUCTS PRIMARY KEY (PRODUCT_KEY),

    CONSTRAINT UK_DIM_PRODUCTS UNIQUE (PRODUCT_ID),

    CONSTRAINT FK_PRODUCT_CATEGORY
        FOREIGN KEY (CATEGORY_KEY)
        REFERENCES DIM_CATEGORY(CATEGORY_KEY),

    CONSTRAINT FK_PRODUCT_BRAND
        FOREIGN KEY (BRAND_KEY)
        REFERENCES DIM_BRAND(BRAND_KEY)
);

-- ==========================================
-- DIM_PRODUCT_IMAGES
-- ==========================================

CREATE OR REPLACE TABLE DIM_PRODUCT_IMAGES (
    IMAGE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    IMAGE_ID NUMBER NOT NULL,

    PRODUCT_KEY NUMBER,

    IMAGE_URL VARCHAR(500),

    IS_PRIMARY BOOLEAN,

    UPLOADED_AT TIMESTAMP_NTZ,

    CONSTRAINT PK_DIM_PRODUCT_IMAGES PRIMARY KEY (IMAGE_KEY),

    CONSTRAINT UK_DIM_PRODUCT_IMAGES UNIQUE (IMAGE_ID),

    CONSTRAINT FK_PRODUCT_IMAGE
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCTS(PRODUCT_KEY)
);

-- ==========================================
-- CREATE OR REPLACE TABLE  (
-- ==========================================

CREATE OR REPLACE TABLE DIM_PRODUCT_VARIANTS (
    VARIANT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    VARIANT_ID NUMBER NOT NULL,

    PRODUCT_KEY NUMBER,

    COLOR VARCHAR(30),
    SIZE VARCHAR(20),
    STORAGE VARCHAR(20),

    SKU VARCHAR(100),

    CONSTRAINT PK_DIM_PRODUCT_VARIANTS PRIMARY KEY (VARIANT_KEY),

    CONSTRAINT UK_DIM_PRODUCT_VARIANTS UNIQUE (VARIANT_ID),

    CONSTRAINT UK_PRODUCT_SKU UNIQUE (SKU),

    CONSTRAINT FK_PRODUCT_VARIANT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCTS(PRODUCT_KEY)
);

// ----------------------------------------------------------------------------------------------------------------------------------
-- ==========================================
-- BRIDGE_PRODUCT_SELLERS
-- ==========================================

USE SCHEMA Seller_Model;

CREATE OR REPLACE TABLE BRIDGE_PRODUCT_SELLERS (
    SELLER_PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    PRODUCT_KEY NUMBER NOT NULL,

    SELLER_KEY NUMBER NOT NULL,

    ITEM_SELLING_PRICE NUMBER(10,2),

    QUANTITY NUMBER,

    DISCOUNT_PERCENTAGE NUMBER(5,2),

    CONSTRAINT PK_BRIDGE_PRODUCT_SELLERS
        PRIMARY KEY (SELLER_PRODUCT_KEY),

    CONSTRAINT UK_PRODUCT_SELLER
        UNIQUE (PRODUCT_KEY, SELLER_KEY),

    CONSTRAINT FK_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES Product_model.DIM_PRODUCTS(PRODUCT_KEY),

    CONSTRAINT FK_SELLER
        FOREIGN KEY (SELLER_KEY)
        REFERENCES DIM_SELLER(SELLER_KEY)
);



-- ==========================================
-- FACT_ORDER_ITEMS -------------------------------------
-- ==========================================
CREATE OR REPLACE TABLE FACT_ORDER_ITEMS (
    ORDER_ITEM_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ORDER_ITEM_ID NUMBER NOT NULL,

    ORDER_KEY NUMBER NOT NULL,
    SELLER_PRODUCT_KEY NUMBER NOT NULL,

    QUANTITY NUMBER,

    UNIT_PRICE NUMBER(10,2),

    COST_PRICE NUMBER(10,2),

    DISCOUNT_AMOUNT NUMBER(10,2),

    TAX_AMOUNT NUMBER(10,2),

    SHIPPING_AMOUNT NUMBER(10,2),

    REVENUE NUMBER(12,2),

    PROFIT NUMBER(12,2),

    MARGIN_PERCENT NUMBER(5,2),

    CONSTRAINT PK_FACT_ORDER_ITEMS
        PRIMARY KEY (ORDER_ITEM_KEY),

    CONSTRAINT UK_FACT_ORDER_ITEMS
        UNIQUE (ORDER_ITEM_ID),

    CONSTRAINT FK_FACT_ORDER_ITEMS_ORDER
        FOREIGN KEY (ORDER_KEY)
        REFERENCES DIM_ORDERS(ORDER_KEY),

    CONSTRAINT FK_FACT_ORDER_ITEMS_SELLER_PRODUCT
        FOREIGN KEY (SELLER_PRODUCT_KEY)
        REFERENCES Seller_model.BRIDGE_PRODUCT_SELLERS(SELLER_PRODUCT_KEY)
);

