-- =============================================================================
-- 1. DIMENSION PROCEDURES
-- =============================================================================

CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_USER()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_USER AS USR
    USING ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS SRC
        ON USR.USER_ID = SRC.USER_ID

    WHEN MATCHED THEN
        UPDATE SET
            USR.FIRST_NAME    = SRC.FIRST_NAME,
            USR.LAST_NAME     = SRC.LAST_NAME,
            USR.MIDDLE_NAME   = SRC.MIDDLE_NAME,
            USR.EMAIL         = SRC.EMAIL,
            USR.PASSWORD_HASH = SRC.PASSWORD_HASH,
            USR.STATUS        = SRC.STATUS,
            USR.CREATED_AT    = SRC.CREATED_AT,
            USR.UPDATED_AT    = SRC.UPDATED_AT

    WHEN NOT MATCHED THEN
        INSERT (USER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL, PASSWORD_HASH, STATUS, CREATED_AT, UPDATED_AT)
        VALUES (SRC.USER_ID, SRC.FIRST_NAME, SRC.LAST_NAME, SRC.MIDDLE_NAME, SRC.EMAIL, SRC.PASSWORD_HASH, SRC.STATUS, SRC.CREATED_AT, SRC.UPDATED_AT);

    RETURN 'DIM_USER LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_ADDRESS()
RETURNS STRING
LANGUAGE SQL
AS 
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_ADDRESS AS ADDR
    USING (
        SELECT
            STR.ADDRESS_ID,
            DU.USER_KEY,
            STR.COUNTRY,
            STR.STATE,
            STR.DISTRICT,
            STR.CITY,
            STR.VILLAGE,
            STR.ZIPCODE,
            STR.ADDRESS_TYPE
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS STR
        INNER JOIN ECOMMERCE.USER_MART.DIM_USER AS DU
            ON STR.USER_ID = DU.USER_ID
    ) AS SRC
        ON ADDR.ADDRESS_ID = SRC.ADDRESS_ID

    WHEN MATCHED THEN
        UPDATE SET
            ADDR.USER_KEY     = SRC.USER_KEY,
            ADDR.COUNTRY      = SRC.COUNTRY,
            ADDR.STATE        = SRC.STATE,
            ADDR.DISTRICT     = SRC.DISTRICT,
            ADDR.CITY         = SRC.CITY,
            ADDR.VILLAGE      = SRC.VILLAGE,
            ADDR.ZIPCODE      = SRC.ZIPCODE,
            ADDR.ADDRESS_TYPE = SRC.ADDRESS_TYPE

    WHEN NOT MATCHED THEN
        INSERT (ADDRESS_ID, USER_KEY, COUNTRY, STATE, DISTRICT, CITY, VILLAGE, ZIPCODE, ADDRESS_TYPE)
        VALUES (SRC.ADDRESS_ID, SRC.USER_KEY, SRC.COUNTRY, SRC.STATE, SRC.DISTRICT, SRC.CITY, SRC.VILLAGE, SRC.ZIPCODE, SRC.ADDRESS_TYPE);

    RETURN 'DIM_ADDRESS LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_MOBILE()
RETURNS STRING
LANGUAGE SQL
AS 
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_MOBILE AS MOB
    USING (
        SELECT 
            STR.MOBILE_ID,
            DU.USER_KEY,
            STR.COUNTRY_CODE,
            STR.PHONE_NUMBER,
            STR.IS_PRIMARY
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS STR
        INNER JOIN ECOMMERCE.USER_MART.DIM_USER AS DU 
            ON STR.USER_ID = DU.USER_ID
    ) AS SRC
        ON MOB.MOBILE_ID = SRC.MOBILE_ID

    WHEN MATCHED THEN 
        UPDATE SET
            MOB.USER_KEY     = SRC.USER_KEY,
            MOB.COUNTRY_CODE = SRC.COUNTRY_CODE,
            MOB.PHONE_NUMBER = SRC.PHONE_NUMBER,
            MOB.IS_PRIMARY   = SRC.IS_PRIMARY

    WHEN NOT MATCHED THEN
        INSERT (MOBILE_ID, USER_KEY, COUNTRY_CODE, PHONE_NUMBER, IS_PRIMARY)
        VALUES (SRC.MOBILE_ID, SRC.USER_KEY, SRC.COUNTRY_CODE, SRC.PHONE_NUMBER, SRC.IS_PRIMARY);

    RETURN 'DIM_MOBILE LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_ROLE()
RETURNS STRING
LANGUAGE SQL
AS 
$$
BEGIN 
    MERGE INTO ECOMMERCE.USER_MART.DIM_ROLE AS TARGET
    USING ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS SRC
        ON TARGET.ROLE_ID = SRC.ROLE_ID

    WHEN MATCHED THEN 
        UPDATE SET 
            TARGET.ROLE_NAME = SRC.ROLE_NAME

    WHEN NOT MATCHED THEN
        INSERT (ROLE_ID, ROLE_NAME)
        VALUES (SRC.ROLE_ID, SRC.ROLE_NAME);

    RETURN 'DIM_ROLE LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_BRIDGE_USR_ROLE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.BRIDGE_USER_ROLE AS TARGET
    USING (
        SELECT DISTINCT
            USR.USER_KEY,
            ROLE.ROLE_KEY
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS SRC
        INNER JOIN ECOMMERCE.USER_MART.DIM_USER AS USR
            ON SRC.USER_ID = USR.USER_ID
        INNER JOIN ECOMMERCE.USER_MART.DIM_ROLE AS ROLE
            ON SRC.ROLE_ID = ROLE.ROLE_ID
    ) AS SRC
        ON TARGET.USER_KEY = SRC.USER_KEY
       AND TARGET.ROLE_KEY = SRC.ROLE_KEY

    WHEN NOT MATCHED THEN
        INSERT (USER_KEY, ROLE_KEY)
        VALUES (SRC.USER_KEY, SRC.ROLE_KEY);

    RETURN 'BRIDGE_USER_ROLE LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_DEVICE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_DEVICE AS TARGET
    USING (
        SELECT DISTINCT
            DEVICE_NAME,
            BROWSER
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
    ) AS SRC
        ON TARGET.DEVICE_NAME = SRC.DEVICE_NAME
       AND TARGET.BROWSER = SRC.BROWSER

    WHEN NOT MATCHED THEN
        INSERT (DEVICE_NAME, BROWSER)
        VALUES (SRC.DEVICE_NAME, SRC.BROWSER);

    RETURN 'DIM_DEVICE LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_DATE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_DATE AS DT
    USING (
        SELECT DISTINCT
            FULL_DATE,
            DAY,
            MONTH,
            QUARTER,
            YEAR,
            DAY_NAME
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
        WHERE FULL_DATE IS NOT NULL
    ) AS SRC
        ON DT.FULL_DATE = SRC.FULL_DATE

    WHEN NOT MATCHED THEN
        INSERT (DATE_KEY, FULL_DATE, DAY, MONTH, QUARTER, YEAR, DAY_NAME)
        VALUES (
            TO_NUMBER(TO_CHAR(SRC.FULL_DATE, 'YYYYMMDD')),
            SRC.FULL_DATE,
            SRC.DAY,
            SRC.MONTH,
            SRC.QUARTER,
            SRC.YEAR,
            SRC.DAY_NAME
        );

    RETURN 'DIM_DATE LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_TIME()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_TIME AS TARGET
    USING (
        SELECT DISTINCT
            HOUR,
            MINUTE,
            SECOND
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
        WHERE HOUR IS NOT NULL
          AND MINUTE IS NOT NULL
          AND SECOND IS NOT NULL
    ) AS SRC
        ON TARGET.HOUR = SRC.HOUR
       AND TARGET.MINUTE = SRC.MINUTE
       AND TARGET.SECOND = SRC.SECOND

    WHEN NOT MATCHED THEN
        INSERT (TIME_KEY, HOUR, MINUTE, SECOND)
        VALUES (
            SRC.HOUR * 10000 + SRC.MINUTE * 100 + SRC.SECOND,
            SRC.HOUR,
            SRC.MINUTE,
            SRC.SECOND
        );

    RETURN 'DIM_TIME LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_IP()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_IP AS TARGET
    USING (
        SELECT DISTINCT IP_ADDRESS
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
        WHERE IP_ADDRESS IS NOT NULL
    ) AS SRC
        ON TARGET.IP_ADDRESS = SRC.IP_ADDRESS

    WHEN NOT MATCHED THEN
        INSERT (IP_ADDRESS)
        VALUES (SRC.IP_ADDRESS);

    RETURN 'DIM_IP LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_LOGIN_STATUS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_LOGIN_STATUS AS TARGET
    USING (
        SELECT DISTINCT LOGIN_STATUS
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
        WHERE LOGIN_STATUS IS NOT NULL
    ) AS SRC
        ON TARGET.LOGIN_STATUS = SRC.LOGIN_STATUS

    WHEN NOT MATCHED THEN
        INSERT (LOGIN_STATUS)
        VALUES (SRC.LOGIN_STATUS);

    RETURN 'DIM_LOGIN_STATUS LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_ACTIVITY()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_ACTIVITY AS TARGET
    USING (
        SELECT DISTINCT ACTIVITY_NAME
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
        WHERE ACTIVITY_NAME IS NOT NULL
    ) AS SRC
        ON TARGET.ACTIVITY_NAME = SRC.ACTIVITY_NAME

    WHEN NOT MATCHED THEN
        INSERT (ACTIVITY_NAME)
        VALUES (SRC.ACTIVITY_NAME);

    RETURN 'DIM_ACTIVITY LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_DIM_NOTIFICATION_TYPE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.DIM_NOTIFICATION_TYPE AS TARGET
    USING (
        SELECT DISTINCT NOTIFICATION_TYPE
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM
        WHERE NOTIFICATION_TYPE IS NOT NULL
    ) AS SRC
        ON TARGET.NOTIFICATION_TYPE = SRC.NOTIFICATION_TYPE

    WHEN NOT MATCHED THEN
        INSERT (NOTIFICATION_TYPE)
        VALUES (SRC.NOTIFICATION_TYPE);

    RETURN 'DIM_NOTIFICATION_TYPE LOAD SUCCESSFUL';
END;
$$;


-- =============================================================================
-- 2. FACT PROCEDURES
-- =============================================================================

CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_FACT_LOGIN()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.FACT_LOGIN AS TARGET
    USING (
        SELECT
            DU.USER_KEY,
            DD.DEVICE_KEY,
            DI.IP_KEY,
            DDATE.DATE_KEY,
            DTIME.TIME_KEY,
            DLS.STATUS_KEY,
            1 AS LOGIN_COUNT
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS SRC
        INNER JOIN ECOMMERCE.USER_MART.DIM_USER AS DU
            ON SRC.USER_ID = DU.USER_ID
        INNER JOIN ECOMMERCE.USER_MART.DIM_DEVICE AS DD
            ON SRC.DEVICE_NAME = DD.DEVICE_NAME
           AND SRC.BROWSER = DD.BROWSER
        INNER JOIN ECOMMERCE.USER_MART.DIM_IP AS DI
            ON SRC.IP_ADDRESS = DI.IP_ADDRESS
        INNER JOIN ECOMMERCE.USER_MART.DIM_DATE AS DDATE
            ON SRC.FULL_DATE = DDATE.FULL_DATE
        INNER JOIN ECOMMERCE.USER_MART.DIM_TIME AS DTIME
            ON SRC.HOUR = DTIME.HOUR
           AND SRC.MINUTE = DTIME.MINUTE
           AND SRC.SECOND = DTIME.SECOND
        INNER JOIN ECOMMERCE.USER_MART.DIM_LOGIN_STATUS AS DLS
            ON SRC.LOGIN_STATUS = DLS.LOGIN_STATUS
    ) AS SRC
        ON TARGET.USER_KEY   = SRC.USER_KEY
       AND TARGET.DEVICE_KEY = SRC.DEVICE_KEY
       AND TARGET.IP_KEY     = SRC.IP_KEY
       AND TARGET.DATE_KEY   = SRC.DATE_KEY
       AND TARGET.TIME_KEY   = SRC.TIME_KEY
       AND TARGET.STATUS_KEY = SRC.STATUS_KEY

    WHEN NOT MATCHED THEN
        INSERT (USER_KEY, DEVICE_KEY, IP_KEY, DATE_KEY, TIME_KEY, STATUS_KEY, LOGIN_COUNT)
        VALUES (SRC.USER_KEY, SRC.DEVICE_KEY, SRC.IP_KEY, SRC.DATE_KEY, SRC.TIME_KEY, SRC.STATUS_KEY, SRC.LOGIN_COUNT);

    RETURN 'FACT_LOGIN LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_FACT_ACTIVITY()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.FACT_ACTIVITY AS TARGET
    USING (
        SELECT
            DU.USER_KEY,
            DA.ACTIVITY_KEY,
            DDATE.DATE_KEY,
            DTIME.TIME_KEY,
            SRC.ACTIVITY_COUNT
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS SRC
        INNER JOIN ECOMMERCE.USER_MART.DIM_USER AS DU
            ON SRC.USER_ID = DU.USER_ID
        INNER JOIN ECOMMERCE.USER_MART.DIM_ACTIVITY AS DA
            ON SRC.ACTIVITY_NAME = DA.ACTIVITY_NAME
        INNER JOIN ECOMMERCE.USER_MART.DIM_DATE AS DDATE
            ON SRC.FULL_DATE = DDATE.FULL_DATE
        INNER JOIN ECOMMERCE.USER_MART.DIM_TIME AS DTIME
            ON SRC.HOUR = DTIME.HOUR
           AND SRC.MINUTE = DTIME.MINUTE
           AND SRC.SECOND = DTIME.SECOND
    ) AS SRC
        ON TARGET.USER_KEY     = SRC.USER_KEY
       AND TARGET.ACTIVITY_KEY = SRC.ACTIVITY_KEY
       AND TARGET.DATE_KEY     = SRC.DATE_KEY
       AND TARGET.TIME_KEY     = SRC.TIME_KEY

    WHEN MATCHED THEN
        UPDATE SET
            TARGET.ACTIVITY_COUNT = SRC.ACTIVITY_COUNT

    WHEN NOT MATCHED THEN
        INSERT (USER_KEY, ACTIVITY_KEY, DATE_KEY, TIME_KEY, ACTIVITY_COUNT)
        VALUES (SRC.USER_KEY, SRC.ACTIVITY_KEY, SRC.DATE_KEY, SRC.TIME_KEY, SRC.ACTIVITY_COUNT);

    RETURN 'FACT_ACTIVITY LOAD SUCCESSFUL';
END;
$$;


CREATE OR REPLACE PROCEDURE ECOMMERCE.CLEAN.SP_LOAD_FACT_NOTIFICATION()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO ECOMMERCE.USER_MART.FACT_NOTIFICATION AS TARGET
    USING (
        SELECT
            DU.USER_KEY,
            DNT.NOTIFICATION_TYPE_KEY,
            DDATE.DATE_KEY,
            DTIME.TIME_KEY,
            SRC.NOTIFICATION_SENT,
            SRC.NOTIFICATION_READ
        FROM ECOMMERCE.CLEAN.CLEAN_USER_STREAM AS SRC
        INNER JOIN ECOMMERCE.USER_MART.DIM_USER AS DU
            ON SRC.USER_ID = DU.USER_ID
        INNER JOIN ECOMMERCE.USER_MART.DIM_NOTIFICATION_TYPE AS DNT
            ON SRC.NOTIFICATION_TYPE = DNT.NOTIFICATION_TYPE
        INNER JOIN ECOMMERCE.USER_MART.DIM_DATE AS DDATE
            ON SRC.FULL_DATE = DDATE.FULL_DATE
        INNER JOIN ECOMMERCE.USER_MART.DIM_TIME AS DTIME
            ON SRC.HOUR = DTIME.HOUR
           AND SRC.MINUTE = DTIME.MINUTE
           AND SRC.SECOND = DTIME.SECOND
    ) AS SRC
        ON TARGET.USER_KEY              = SRC.USER_KEY
       AND TARGET.NOTIFICATION_TYPE_KEY = SRC.NOTIFICATION_TYPE_KEY
       AND TARGET.DATE_KEY              = SRC.DATE_KEY
       AND TARGET.TIME_KEY              = SRC.TIME_KEY

    WHEN MATCHED THEN
        UPDATE SET
            TARGET.NOTIFICATION_SENT = SRC.NOTIFICATION_SENT,
            TARGET.NOTIFICATION_READ = SRC.NOTIFICATION_READ

    WHEN NOT MATCHED THEN
        INSERT (USER_KEY, NOTIFICATION_TYPE_KEY, DATE_KEY, TIME_KEY, NOTIFICATION_SENT, NOTIFICATION_READ)
        VALUES (SRC.USER_KEY, SRC.NOTIFICATION_TYPE_KEY, SRC.DATE_KEY, SRC.TIME_KEY, SRC.NOTIFICATION_SENT, SRC.NOTIFICATION_READ);

    RETURN 'FACT_NOTIFICATION LOAD SUCCESSFUL';
END;
$$;
